-- V3: Fix SERIAL -> BIGSERIAL to match JPA Long id fields
ALTER TABLE users ALTER COLUMN id TYPE BIGINT;
ALTER TABLE api_keys ALTER COLUMN id TYPE BIGINT;
ALTER TABLE products ALTER COLUMN id TYPE BIGINT;
ALTER TABLE user_profiles ALTER COLUMN id TYPE BIGINT;
ALTER TABLE sessions ALTER COLUMN id TYPE BIGINT;
ALTER TABLE orders ALTER COLUMN id TYPE BIGINT;
ALTER TABLE intent_samples ALTER COLUMN id TYPE BIGINT;
ALTER TABLE conversation_messages ALTER COLUMN id TYPE BIGINT;
